### ISSUE TITLE
Documentation error in example.cpp

### ISSUE THREAD

**Issue by ranchmed** [Blake-Madden/OleanderStemmingLibrary#5]
Thanks for making this code available to the open source community. I am evaluating the library for inclusion in a personal project that I am doing. In looking at the source code for the example.cpp, I did notice a mistake. On line 40:

    //now the variable "word" should equal "document"

should be

    //now the variable "word" should equal "transport"

Thanks again for making this available!

**Comment by OleanderSoftware** [comment]
Sorry for the delay, and thanks for spotting this.

Should be "documentation" in the initial value, "transportation" shouldn't have been there; fixed now.  Thanks, and good luck with your project!!!
